### ISSUE TITLE
Please add license information

### ISSUE THREAD

**Issue by sergeyatveritone** [davidisaaclee/interval-tree#1]
Could you please add license information to the project, so people know if they can use your package?

Thank you!

**Comment by davidisaaclee** [comment]
Hi @sergeyatveritone – sorry for the delay here. I just added an MIT License in this commit: https://github.com/davidisaaclee/interval-tree/commit/a4d443b0fca3c3d72bac7b51accd17cba3d77db4

I hope this is permissive enough for your use. I don't have a lot of experience with licensing, and I don't really care about the licensing of this library, so let me know what license you would prefer if this isn't sufficient and I'd probably be happy to switch to it.

**Comment by sergeyatveritone** [comment]
That's perfect. Thank you very much!
